name: ci

on:
  pull_request:

jobs:
  eslint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: npm install
      - name: Run ESLint
        run: npm run lint
  component-tests:
    needs: eslint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install frontend modules
        uses: cypress-io/github-action@v6
        with:
          install-command: npm install
          runTests: false
      - name: Run frontend component tests 🧪
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:components
  e2e-tests:
    needs: component-tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install frontend modules
        uses: cypress-io/github-action@v6
        with:
          install-command: npm run install
          runTests: false
      - name: Run E2E tests 🧪
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          command: npm run test:e2e
