name: ci

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  eslint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: npm install
      - name: Run ESLint
        run: npm run lint
  component-and-e2e-tests:
    needs: eslint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install frontend modules
        uses: cypress-io/github-action@v6
        with:
          install-command: npm install
          runTests: false
      - name: Create mochawesome-report directory
        run: mkdir -p mochawesome-report
      - name: Run E2E tests 🧪
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          command: npm test
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
